spring.datasource.url=${VIPPELA_DB_URL}
spring.datasource.username=${VIPPELA_DB_USER}
spring.datasource.password=${VIPPELA_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
server.port=${PORT:8080}