spring.datasource.url=jdbc:postgresql://localhost:5432/vippela_db
spring.datasource.username=postgres
spring.datasource.password=R@fa1001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080